biratdatta/Webpage-Maker

Index.html
Added a new topic Lists in HTML
Please accept and label it as HACKTOBERFEST-ACCEPTED
=> Added Lists in HTML

CSS/style.css, Index.html
Please review and label it as hacktoberfest accepted
=> Added Table Section

CSS/style.css, Index.html
Please review and label it as hacktober fest accepted
=> added symbols in html

Index.html
pls review and add hacktoberfest label and hacktoberfest accepted label
=> added yt section

Buttons/button.css, Buttons/index.html
- Added various types of CSS buttons.
=> Added Buttons page

CSS/style.css
Added new class such that the whole content looks beautiful
=> Updated style.css

Learn.md
=> Updated Learn.md by adding form

AnimatedText/index.html, AnimatedText/style.css
I have added some animated text as per the issue #26 
https://user-images.githubusercontent.com/47363596/193627331-fdf4e07a-e494-4680-8055-9d6a3640dce2.mov
please merge the PR with hacktoberfest-accepted label
=> Added animated text 

Full HTML CHEATSHEET/Sourodip20kar.md
=> Updated HTML Cheatsheet

Buttons/index2.css, Buttons/index2.html
Hey @biratdatta . I've added some more button animations to this Cheat sheet.
FIXES #29 
I've added 2 files in the Buttons folder :- 
1. index2.html
2. index2.css
In these 2 files lies the complete code(HTML +CSS) of the added button animations. I hope would be pretty helpful for everyone.
Thanks :)
=> Added some more button animations

Full HTML CHEATSHEET/Sourodip20kar.md
#43 
Added a Deperecated Tags section on the HTML cheat sheet based upon w3 documentation.
Also corrected some identation at HTML graphics section.
Hope it's useful!
=> feat: Added HTML Deprecated Tags on the cheatsheet

CSS Cheatsheet.md
Hey,
I'm Nihal and I'm adding CSS CheatSheet.
This will very beneficial for beginner who learning web development..
CSS (Cascading Style Sheets) is used to style and layout web pages — for example, to alter the font, color, size, and spacing of your content, split it into multiple columns, or add animations and other decorative features.
=> Create CSS Cheatsheet.md

Full HTML CHEATSHEET/Sourodip20kar.md
Added Youtube video Embedding Code in HTML cheatsheet.
=>  Added Youtube embeddingUpdate Sourodip20kar.md

Complete [HTML + CSS] CheatSheet.txt, JS Personal Notes.txt
Beginner friendly cheatsheet for HTML and CSS (Personally made, while revising an 8hr course)
=> Zero to Hero Cheatsheet for HTML and CSS

JS/Cheat Sheet of JS/cheat sheet.md
Cheat Sheet has been added for JavaScript #57
=> Added Cheat Sheet for JavaScript

Full HTML CHEATSHEET/Sourodip20kar.md
Added some scripts which allows to use the mathematical symbols in HTML. Wish to add stuff like greek alphabets and much more. Great project.
=> Added HTML Mathematical Symbols. 

NumGuesserGame-2Player/NumGuesser.css, NumGuesserGame-2Player/NumGuesser.js, NumGuesserGame-2Player/README.txt, NumGuesserGame-2Player/index.html
=> added 2 player NumGuesserGame

Git CheatSheet/gitCheatSheet.md
Created git cheat sheet updated the folder . Check the changes .
=> Updated folder with git cheat sheet

all-you-need-in-html-main/README.md, all-you-need-in-html-main/index.html, all-you-need-in-html-main/package.json, all-you-need-in-html-main/sandbox.config.json
This repository contains all you need for starting an html page 
1. h tag
2. p tag 
3. lists
4. forms
5. colors
6. footer
7. br , hr
8. comments
9. table
=> HTML all basic tags you need see code and output

SECOND PAGE.html
I have added Marquee tag in the Second Page of the project.
resolves #50
=> Added Marquee

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE.md, Readme.md
**Issue #70**
- Improved the **Contributing.md file**.
- Acknowledge the **contributors** by mentioning them in README file which is ***updated automatically***.
- Added **LICENSE.md** to claim the hard work of the project as yours.
=> Improved Contributing.md and added Contributor section in README

Buttons/buttons.html, Navbars/4th/nav.html
I added button and navbar example.
Please accept my PR.
=> Added button and navbar

Login page/index.html, Login page/script.js, Login page/style.css
=> Login page added

Number_Guessing_Game/app.js, Number_Guessing_Game/index.html, Number_Guessing_Game/style.css
=> number guesser added

AnimatedText/textanime.html
=> Addded Text animation

MYSQL Cheatsheet.md
Created a detailed MYSQL Cheatsheet which has 
MYSQL COMMAND LINE COMMANDS
MYSQL DATABASE COMMANDS (DATA DEFINITION LANGUAGE;DDL)
MySQL Table commands(DDL)
MySQL DML(Data Manipulation Language) Commands
MySQL DATA TYPES
MySQL AGGREGATE FUNCTIONS
INDEXES AND VIEWS IN MySQL
TRIGGERS IN MYSQL
INBUILT FUNCTIONS IN MySQL
Hey @biratdatta , can you please merge this pull request and label it as hacktoberfest or hacktoberfest-accepted as a part of my hacktoberfest 2022 contributions?
=> Created a detailed MYSQL Cheatsheet

Animated_Login_Page/index.html, Animated_Login_Page/main.css
New animated login page added and when animated login button hover it gives bright blue color which looks so beautiful and attractive.
Issue #91 resolved
Some screenshots:
=> new animated login page added

Linux CheatSheet.md, NPM Cheat Sheet.md
Hey @biratdatta , can you please merge this pull request and label it as hacktoberfest or hacktoberfest-accepted as a part of my hacktoberfest 2022 contributions?
I have added a cheat sheet of of important linux commands which will be helpful to developers who use Linux.
=> Created Linux Cheatsheet of important linux commands

django cheatsheat.md
added some tips and tricks for Django framework
=> Created django cheatsheat.md #133

Readme.md
Updated Readme.md file, and added links of the new cheatsheet.
@biratdatta Kindly check.
=> Updated Readme.md  #135

swift cheatsheet.md
This is a cheat sheet for swift. Kindly merge it.
=> Created swift cheatsheet.md

Navbars/5th/navBar.html
In the navbar folder, I have added a new navbar with animation effect on hover and a search box.
Please merge it under hacktoberfest. THANKS!!
=> added a navbar

mongoose-cheatsheet.md
I have added a mongoose cheatsheet which closes #161
=> added mongoose cheatsheet

HTML/Index.html
snapchat icon was not visible previously so made some changes and updated the placeholder values of the contact us section.
=> updated Index.html in HTML folder

simple_html_and_css_webpage/new 1.html
made a simple webpage using html and css basics.
=> simple webpage

Contact Us Form/index.html, Contact Us Form/style.css, Price Template/index.html, Price Template/styles.css
issue: #155
Added Contact Us form and Price Template
=> Adding Contact Us form and Price Template

Bootstrap Cheatsheet.md
Added the bootstrap cheat sheet readme file. Please do check it out.
=> added Bootstrap cheatsheet

React Js Cheatsheet/reactjs_cheatsheet.md
=> Added useContext content for reactjs cheatsheet

Readme.md
- Remove duplicated Code of Conduct hyperlink
- Remove `=======` after roadmaps topic
No applicable.
=> Remove duplicated Code of Conduct

switch/index.html, switch/style.css
=> upload basic switch css

HTML/Learn.md
Added forms in HTML in Learn.md file.
=> Added forms in HTML

CRUD Project/index.html, CRUD Project/script.js, CRUD Project/style.css
CRUD Project Using HTML, CSS, Javascript 
you can add, update, edit, and delete on a client side are
=> I added a CRUD Project using javascript

Buttons/button.css, Buttons/index.html
Hey there, I have completed working on the button and this is the pull request for it.
Issue no is 184
=> New Button added to Button Templates (Issue 184)

new mongodb cheat sheet/mongodb.md.md
I have added new mongodb cheat sheet.
=> Add new mongodb cheat sheet

django cheatsheat.md
Improved and fixed syntaxes in the cheathseet.md
[x] Beautified the django cheatsheet.
[x] Fixed wrong syntax
=> Updated django cheatsheet

paymentform.css, paymentform.html
Simple payment form template created using Html and CSS!! 
issue #205
=> Added Payment Form(html & CSS)

Buttons/HoverSpanbutton.html
=> added a animated button

blurry-image-loader/index.html, blurry-image-loader/script.js, blurry-image-loader/style.css
I have added a project made using HTML and CSS.
In this project my background image blur reduces from 30% to 0% as the loader loads from 0% to 100%
=> Project added

Covid Resource Site/about.html, Covid Resource Site/disclaimer.html, Covid Resource Site/index.html, Covid Resource Site/quicktips.html, Covid Resource Site/statewise.html
=> Added COVID-19 Resource Site

Readme.md
=> readme-edit

CGPA_calculator.html
Created new file CGPA_calculator.html
Happy coding.
=> Created a new file CGPA_calculator.html

ImageUploader/index.html, ImageUploader/script.js, ImageUploader/style.css
=> feat : add basic image uploader

Readme.md, conda-cheatsheet.md
=> Added a cheatsheet for managing conda

CSS Cards Template/index.html, CSS Cards Template/styles.css
Adding CSS Card Template with hover effects
=> Adding CSS Card Template

jumpinganimation/index.html, jumpinganimation/style.css
=> Jumping animation

CSS Card Hover Animation/index.html, CSS Card Hover Animation/style.css
=> add card hover animation
